# -*- coding: utf-8 -*-
"""assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OMnQJQOczjw6ALhk_YuA4SbQ3nCK8g_o
"""

#1. To find a URL in a sentence.

import re
def find_url(text):
  return re.findall(r'https?://[^\s]+' , text)
found=find_url(" I love spending time at https://www.xy123z.com/")
print("Found URLs:", found)

#2. Get Email id from the sentence.

import re
def find_email(text):
  return re.findall(r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}",text )
found= find_email("My email id is xyz111@gmail.com.")
print("Found Emails:", found)

#3.	To find the hashtags.

import re
def find_hashtag(text):
  return re.findall(r"#\w+",text)
found=find_hashtag("I love spending time at #xy123z")
print("Found Hashtags:", found)

#4.	To find the mentions in a sentence.

import re
def find_mention(text):
  return re.findall(r"@\w+",text)
found=find_mention("@Ajit, please help me")
print("Found Mentions:", found)

#5.	To find numbers in a sentence.

import re
def find_number(text):
  return re.findall(r"\d+",text)
found=find_number("8853147 sq. km of area washed away in floods")
print("Found Number:", found)

#6.	To find punctuations in a sentence.

import re
def find_punctuation(text):
  return re.findall(r"[^\w\s]",text)
found=find_punctuation("Corona virus killed #24506 people. #Corona is un(tolerable)")
print("Found Punctuation:", found)

#7.	To Validate PAN Number use the below code:.

import re
def validate_pan(pan_number):
   re.match(r'^[A-Z]{5}[0-9]{4}[A-Z]$', pan_number)
found=validate_pan("lEcGD012eg")
print("Found PAN:", found)